### ISSUE TITLE
Support custom JsonProperty annotation in case class interfaces

### ISSUE THREAD

**Issue by azell** [Randgalt/halva#19]
I would like to define a case class such as:

```
@CaseClass(json = true)
public interface JsonTest
{
    @JsonProperty("first_name")
    String firstName();
    @JsonProperty("last_name")
    String lastName();
    int age();
}
```

Not sure how much halva wants to expose a dependency on Jackson, in terms of the actual annotation used by the interface.

**Comment by Randgalt** [comment]
I guess the `json` attribute could be an enum that controls naming. e.g. `NONE, STANDARD, LOWERCASE`. But I worry about supporting a ton of different naming conventions. I _think_ though that you can add the annotations manually. I'll do a test when I get a chance.

**Comment by azell** [comment]
Great, and I am guessing that the JsonIgnore / JsonIgnoreProperties annotations would also be useful.

**Comment by Randgalt** [comment]
I'd appreciate a PR or at least a straw-man design

**Comment by azell** [comment]
Fair enough, let me start reading the case class code.

**Comment by Randgalt** [comment]
I did some experimenting and it looks like Jackson will use `@JsonProperty` annotations set in the parent interface. So, we could have an option to `@CaseClass(json = true` that sets all Jackson annotations exception `@JsonProperty`s so that users can override them. Or maybe, the annotation processor could just not set `@JsonProperty` if the parent interface already has it.

**Comment by azell** [comment]
I see a couple of phases:

1. When generating the JsonProperty annotation in `Templates.addField`, check if the method already has a JsonProperty annotation attached to it.  If so, either skip the annotation in the generated code, or copy it from the interface.
2. Support other Jackson annotations such as JsonIgnore by checking for other annotations on the method by name, or by the JacksonAnnotation type.

For number 1, I need to check if all of the required metadata is passed to `addField`.  The metadata would include the class and method.

**Comment by azell** [comment]
One thing I have been bitten by before is depending on key order in the generated JSON.  Ex:

```
        String json = new ObjectMapper().writeValueAsString(object);
        Assert.assertEquals("{\"age\":32,\"type\":\"large\",\"nombre\":\"me\"}", json);
```

A way around this is:

```
Map<String, Object> rhs = mapper.readValue(str, type);
// where lhs is JsonWithOverridesCase instance or similar
Assert.assertEquals(mapper.valueToTree(lhs), mapper.valueToTree(rhs));
```

**Comment by Randgalt** [comment]
I don't use a single ObjectMapper because it's just a test. FYI

**Comment by azell** [comment]
I know, just my OCD / DRY kicking in.
