### ISSUE TITLE
Support type aliases of concrete types

### ISSUE THREAD

**Issue by Alex-At-Home** [Randgalt/halva#23]
Currently can only type alias interfaces

eg Common concrete cases include `String`, `LinkedList`, `fj.data.List`

**Comment by Randgalt** [comment]
`String` is `final`. There's no way to alias it that I can think of :(

**Comment by Alex-At-Home** [comment]
er yes, actually Int/Double/etc are the more common uses in scala (eg `Double` -> `Weight`), of course they have the same `final` issue though a more tractable interface you could simply re-implement. Anyway the main cases were the various collections implementations, `String` was just a throw-out-there thought

**Comment by Randgalt** [comment]
I should probably override the parent constructors.

**Comment by Randgalt** [comment]
Also, per #24 - when wrapping methods that return the parent type, wrap in the aliased type.
