### ISSUE TITLE
Should (can?) type aliases also "override" the static members to "fix" the return type

### ISSUE THREAD

**Issue by Alex-At-Home** [Randgalt/halva#29]
Eg say I have

```
List<T> {
   static List<T> from(T... ts) { /*...*/ }
   //...
}
```

and I do 
`@TypeAlias IntList extends List<Integer>`

then I'd probably like to be able to do

`IntList il = IntList.from(1, 2, 3);` vs `IntList il = IntList.IntList(IntList.from(1, 2, 3));`

(You can just ignore anything that doesn't return the aliased type)

**Comment by Randgalt** [comment]
Java doesn't support overloading static methods, or does it?

**Comment by Alex-At-Home** [comment]
It's not really overloading, it's just hiding; if you have

```
class A { 
static int f() { return  1; }
}
class B extends A { 
static int f() { return  2; }
}
class C extends A { 
}
```

Then

```
A.f() returns 1
B.f() returns 2
C.f() returns 1
```

as you'd expect. Which is fine for what we want here.

**Comment by Alex-At-Home** [comment]
Hmm nvm that doesn't seem to be true, odd I'm sure I've written code that used that in the past. The IDE agrees with me fwiw but javac gets the final say :)

Closing this while I lick my wounds and try to come up with a process I like for using the `alias Stack List<Integer>` construct!
